markdown: kramdown
pygments: true
permalink: /posts/:title
exclude: ["README.md", "blog.sublime-project", "blog.sublime-workspace"]
rdiscount:
  extensions:
    - autolink      # greedily urlify links
    - footnotes     # footnotes
    - smart         # typographic substitutions with SmartyPants
name: Thomas Chapeaux
url: http://thomaschapeaux.be
description: I like clean code, peforming improv, and YOU
twitter: bafaltom
github: "tchapeaux"
linkedin: thomaschapeaux
gravatar_url: http://gravatar.com/avatar/60b655da1740bad9ddcdac56dac3a5a6
